SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS CIP_ATTACHFILE;
DROP TABLE IF EXISTS CIP_AUTHORITY_MEMBER;
DROP TABLE IF EXISTS CIP_MENU_AUTHORITY;
DROP TABLE IF EXISTS CIP_AUTHORITY;
DROP TABLE IF EXISTS CIP_COMMON_CODE;
DROP TABLE IF EXISTS CIP_MEMBER;
DROP TABLE IF EXISTS CIP_MENU;
DROP TABLE IF EXISTS CIP_MULTI_BOARD;
DROP TABLE IF EXISTS CIP_ORGANIZATION;




/* Create Tables */

-- 파일 정보
CREATE TABLE CIP_ATTACHFILE
(
	-- 파일을 N:N 관계로 연계 위해 추가
	ATTACHFILE_SEQ varchar(40) NOT NULL COMMENT '첨부파일 일련번호',
	-- 원본레코드 UNIQUE SEQ, 상담일지는 member_seq
	SOURCE_UNIQUE_SEQ varchar(40) NOT NULL COMMENT '원본레코드 UNIQUE SEQ',
	-- 첨부파일 유형
	ATTACHFILE_TYPE varchar(40) COMMENT '첨부파일 유형',
	-- 원본파일_명
	ORGINALFILE_NAME varchar(200) NOT NULL COMMENT '원본 파일명',
	-- 첨부 파일명
	PHYSICALFILE_NAME varchar(200) NOT NULL COMMENT '첨부 파일명',
	-- 썸네일 첨부파일명
	THUMBNAIL_NAME varchar(500) COMMENT '썸네일 첨부파일명',
	-- 첨부파일 저장경로
	ATTACHFILE_PATH varchar(500) COMMENT '첨부파일 저장경로',
	-- 첨부파일 크기
	ATTACHFILE_SIZE decimal COMMENT '첨부파일 크기',
	ATTACHFILE_HEIGHT decimal COMMENT '파일 높이',
	ATTACHFILE_WIDTH decimal COMMENT '파일 폭',
	-- 등록자SEQ
	REGISTER_SEQ varchar(50) NOT NULL COMMENT '등록자SEQ',
	-- 등록일자
	REGISTRY_DATE varchar(20) NOT NULL COMMENT '등록일자',
	MODIFIER_SEQ varchar(40) NOT NULL COMMENT '수정자_SEQ',
	-- 수정일자
	MODIFY_DATE varchar(20) NOT NULL COMMENT '수정일자',
	PRIMARY KEY (ATTACHFILE_SEQ)
) COMMENT = '파일 정보';


-- 권한 종류
CREATE TABLE CIP_AUTHORITY
(
	-- 권한 코드
	AUTHORITY_ID varchar(40) NOT NULL COMMENT '권한 코드',
	-- 명칭
	NAME varchar(1000) NOT NULL COMMENT '명칭',
	DESCRIPTION varchar(1000) COMMENT '코드설명',
	-- 사용 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용 여부',
	-- 등록자SEQ
	REGISTER_SEQ varchar(50) NOT NULL COMMENT '등록자SEQ',
	-- 등록일자
	REGISTRY_DATE varchar(20) NOT NULL COMMENT '등록일자',
	MODIFIER_SEQ varchar(40) NOT NULL COMMENT '수정자_SEQ',
	-- 수정일자
	MODIFY_DATE varchar(20) NOT NULL COMMENT '수정일자',
	PRIMARY KEY (AUTHORITY_ID)
) COMMENT = '권한 종류';


-- 사용자별 권한들
CREATE TABLE CIP_AUTHORITY_MEMBER
(
	-- 권한 코드
	AUTHORITY_ID varchar(40) NOT NULL COMMENT '권한 코드',
	-- 회원_SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원_SEQ',
	-- 등록자SEQ
	REGISTER_SEQ varchar(50) NOT NULL COMMENT '등록자SEQ',
	-- 등록일자
	REGISTRY_DATE varchar(20) NOT NULL COMMENT '등록일자',
	MODIFIER_SEQ varchar(40) NOT NULL COMMENT '수정자_SEQ',
	-- 수정일자
	MODIFY_DATE varchar(20) NOT NULL COMMENT '수정일자',
	UNIQUE (AUTHORITY_ID, MEMBER_SEQ)
) COMMENT = '사용자별 권한들';


-- 공통코드
CREATE TABLE CIP_COMMON_CODE
(
	-- 공통 코드_ID(사용자 입력 가능)
	COMMON_CODE_ID varchar(40) NOT NULL COMMENT '공통 코드_ID',
	-- 명칭
	NAME varchar(1000) NOT NULL COMMENT '명칭',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	-- 속성_1 
	ATTRIBUTION_1 varchar(60) COMMENT '속성_1',
	-- 속성_2
	ATTRIBUTION_2 varchar(60) COMMENT '속성_2',
	DESCRIPTION varchar(1000) COMMENT '코드설명',
	-- 삭제불가(초기 시스템 코드 or 카테고리)
	SYSTEM_CODE_YN varchar(40) DEFAULT 'N' NOT NULL COMMENT '초기 시스템 코드 여부',
	-- 사용 여부
	USE_YN varchar(40) NOT NULL COMMENT '사용 여부',
	-- 공통 코드_ID(사용자 입력 가능)
	PARENT_COMMON_CODE_ID varchar(40) COMMENT '상위 공통 코드 ID',
	-- 등록자SEQ
	REGISTER_SEQ varchar(50) NOT NULL COMMENT '등록자SEQ',
	-- 등록일자
	REGISTRY_DATE varchar(20) NOT NULL COMMENT '등록일자',
	MODIFIER_SEQ varchar(40) NOT NULL COMMENT '수정자_SEQ',
	-- 수정일자
	MODIFY_DATE varchar(20) NOT NULL COMMENT '수정일자',
	PRIMARY KEY (COMMON_CODE_ID)
) COMMENT = '공통코드';


-- 회원정보
CREATE TABLE CIP_MEMBER
(
	-- 회원_SEQ
	MEMBER_SEQ varchar(40) NOT NULL COMMENT '회원_SEQ',
	-- 회원_ID
	MEMBER_ID varchar(50) NOT NULL COMMENT '회원 ID',
	-- 암호
	PASSWORD varchar(100) NOT NULL COMMENT '암호',
	-- 암호화된 암호
	CRYPT_PASSWORD varchar(100) COMMENT '암호화된 암호',
	-- 명칭
	NAME varchar(1000) NOT NULL COMMENT '명칭',
	-- EMAIL
	EMAIL varchar(1000) COMMENT 'EMAIL',
	-- 휴대폰번호
	CELLPHONE varchar(20) COMMENT '휴대폰번호',
	-- 등록자SEQ
	REGISTER_SEQ varchar(50) NOT NULL COMMENT '등록자SEQ',
	-- 등록일자
	REGISTRY_DATE varchar(20) NOT NULL COMMENT '등록일자',
	MODIFIER_SEQ varchar(40) NOT NULL COMMENT '수정자_SEQ',
	-- 수정일자
	MODIFY_DATE varchar(20) NOT NULL COMMENT '수정일자',
	-- 조직 일련번호
	ORGANIZATION_SEQ varchar(50) NOT NULL COMMENT '조직 일련번호',
	PRIMARY KEY (MEMBER_SEQ)
) COMMENT = '회원정보';


-- 메뉴 마스터 정보
CREATE TABLE CIP_MENU
(
	-- 메뉴 코드 SEQ
	MENU_SEQ varchar(40) NOT NULL COMMENT '메뉴 코드 SEQ',
	-- 명칭
	NAME varchar(1000) NOT NULL COMMENT '명칭',
	-- 정렬순서
	ORDER_NUMBER decimal DEFAULT 1 NOT NULL COMMENT '정렬순서',
	-- 메뉴 주소
	MENU_URI varchar(500) COMMENT '메뉴 주소',
	-- 사용 여부
	USE_YN varchar(40) COMMENT '사용 여부',
	-- 메뉴 코드 SEQ
	PARENT_MENU_SEQ varchar(40) COMMENT '상위 메뉴 코드 SEQ',
	-- 등록자SEQ
	REGISTER_SEQ varchar(50) NOT NULL COMMENT '등록자SEQ',
	-- 등록일자
	REGISTRY_DATE varchar(20) NOT NULL COMMENT '등록일자',
	MODIFIER_SEQ varchar(40) NOT NULL COMMENT '수정자_SEQ',
	-- 수정일자
	MODIFY_DATE varchar(20) NOT NULL COMMENT '수정일자',
	PRIMARY KEY (MENU_SEQ)
) COMMENT = '메뉴 마스터 정보';


-- 메뉴 따른 권한
CREATE TABLE CIP_MENU_AUTHORITY
(
	-- 권한 코드
	AUTHORITY_ID varchar(40) NOT NULL COMMENT '권한 코드',
	-- 메뉴 코드 SEQ
	MENU_SEQ varchar(40) NOT NULL COMMENT '메뉴 코드 SEQ',
	-- 등록자SEQ
	REGISTER_SEQ varchar(50) NOT NULL COMMENT '등록자SEQ',
	-- 등록일자
	REGISTRY_DATE varchar(20) NOT NULL COMMENT '등록일자',
	MODIFIER_SEQ varchar(40) NOT NULL COMMENT '수정자_SEQ',
	-- 수정일자
	MODIFY_DATE varchar(20) NOT NULL COMMENT '수정일자',
	UNIQUE (AUTHORITY_ID, MENU_SEQ)
) COMMENT = '메뉴 따른 권한';


-- 멀티게시판
CREATE TABLE CIP_MULTI_BOARD
(
	-- 게시물 일련번호
	MULTI_BOARD_SEQ varchar(40) NOT NULL COMMENT '게시물 일련번호',
	-- 제목
	TITLE varchar(4000) COMMENT '제목',
	-- 내용/댓글
	CONTENT varchar(4000) NOT NULL COMMENT '내용/댓글',
	-- 시작일시 (공지 등)
	START_DATE varchar(20) COMMENT '시작일시 (공지 등)',
	-- 종료일시 (공지 등)
	END_DATE varchar(20) COMMENT '종료일시 (공지 등)',
	-- 등록자SEQ
	REGISTER_SEQ varchar(50) NOT NULL COMMENT '등록자SEQ',
	-- 등록일자
	REGISTRY_DATE varchar(20) NOT NULL COMMENT '등록일자',
	MODIFIER_SEQ varchar(40) NOT NULL COMMENT '수정자_SEQ',
	-- 수정일자
	MODIFY_DATE varchar(20) NOT NULL COMMENT '수정일자',
	-- 상위 게시물 일련번호
	PARENT_MULTI_BOARD_SEQ varchar(40) COMMENT '상위 게시물 일련번호',
	CONSTRAINT PK_MULTI_BOARD PRIMARY KEY (MULTI_BOARD_SEQ)
) COMMENT = '멀티게시판';


-- 그룹/조직/부서 구조도
CREATE TABLE CIP_ORGANIZATION
(
	-- 조직 일련번호
	ORGANIZATION_SEQ varchar(50) NOT NULL COMMENT '조직 일련번호',
	-- 명칭
	NAME varchar(1000) NOT NULL COMMENT '명칭',
	-- 대표 전화번호
	TELEPHONE varchar(40) COMMENT '대표 전화번호',
	-- 정렬순서
	ORDER_NUMBER decimal COMMENT '정렬순서',
	-- 상위 조직 일련번호
	PARENT_ORGANIZATION_SEQ varchar(50) COMMENT '상위 조직 일련번호',
	CONSTRAINT PK_ORGANIZATION PRIMARY KEY (ORGANIZATION_SEQ)
) COMMENT = '그룹/조직/부서 구조도';



/* Create Foreign Keys */

ALTER TABLE CIP_AUTHORITY_MEMBER
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES CIP_AUTHORITY (AUTHORITY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIP_MENU_AUTHORITY
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES CIP_AUTHORITY (AUTHORITY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIP_COMMON_CODE
	ADD FOREIGN KEY (PARENT_COMMON_CODE_ID)
	REFERENCES CIP_COMMON_CODE (COMMON_CODE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIP_AUTHORITY_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES CIP_MEMBER (MEMBER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIP_MENU
	ADD FOREIGN KEY (PARENT_MENU_SEQ)
	REFERENCES CIP_MENU (MENU_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIP_MENU_AUTHORITY
	ADD FOREIGN KEY (MENU_SEQ)
	REFERENCES CIP_MENU (MENU_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIP_MULTI_BOARD
	ADD FOREIGN KEY (PARENT_MULTI_BOARD_SEQ)
	REFERENCES CIP_MULTI_BOARD (MULTI_BOARD_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIP_MEMBER
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES CIP_ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIP_ORGANIZATION
	ADD FOREIGN KEY (PARENT_ORGANIZATION_SEQ)
	REFERENCES CIP_ORGANIZATION (ORGANIZATION_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



